### PR TITLE
tidied the indentation

### PR DESCRIPTION
**Pull request by ben-vandelaar**
Tidied the indentation, can someone please check before we push it to the master branch,

Cheers.

### CODE REVIEW

**Review by kyokopl — COMMENTED** [review]
Hey Ben, html is looking good. Consider tidying up the spaces between links in rows 120-127. I hope this makes sense. That way it will look cleaner and take up less room. Everything else looks good. Mention me in slack kyoko_p_kakapo when you have commit changes and I will be happy to accept them and clean up by deleting your tidying branch as per 2.5 task. I have also added my link to pull request if you have not reviewed another yet. Thanks

**Comment by ben-vandelaar** [comment]
Thanks will get to it now. I've reviewed someone else's already but if no one gets to yours I'll happily give it a look over.

**Review by kyokopl — APPROVED** [review]
Looks good Ben!

**Comment by kyokopl** [comment]
woops - you may need to add me as collaborator to accept the request.

**Comment by ben-vandelaar** [comment]
Awesome thank you!

**Pull request merged**
